import Head from "next/head";
import { AgentView } from "../components/AgentView";

export default function Home() {
  return (
    <>
      <Head>
        <title>Convo-Lang NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AgentView/>
    </>
  );
}
