// https://en.wikipedia.org/wiki/List_of_Unicode_characters#Arrows


export const cIcon={
    left:'⏴',
    right:'⏵',
    up:'⏶',
    down:'⏷',
    triStar:'⁂',
    dotLg:'⏺',
    dot:'•',
    dotDot:'‥',
    dotOutline:'◦',
    enDash:'–',
    emDash:'—',
    horizontalBar:'―',
    doubleLowLine:'‗',
    leftSingleQuote:'‘',
    rightSingleQuote:'’',
    singleLow9Quote:'‚',
    leftDoubleQuote:'“',
    rightDoubleQuote:'”',
    doubleLowQuote:'„',
    doubleDagger:'‡',
    horizontalEllipsis:'…',
    perMilleSign:'‰',
    doublePrime:'″',
    singleLeftPointingAngleQuote:'‹',
    singleRightPointingAngleQuote:'›',
    doubleExclamationMark:'‼',
    fractionSlash:'⁄',
    tironianEtSign:'⁊',
    gpt:'֍',
    leftRoundCap:'◖',
    rightRoundCap:'◗',
    close:'✕',
} as const;